# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lapply1 <- function(input, f) {
    .Call('_DLFM2_lapply1', PACKAGE = 'DLFM2', input, f)
}

